version: "3"
services:
  auth:
    # build: ./auth-api
    image: ruslanguns/eks-auth:latest
    ports:
      - "8000:3000"
    environment:
      TOKEN_KEY: "shouldbeverysecure"
  users:
    # build: ./users-api
    image: ruslanguns/eks-users:latest
    ports:
      - "8080:3000"
    environment:
      MONGODB_CONNECTION_URI: "mongodb+srv://kub-sample:kub-sample@ic-core-server-001-eu-c.okxlr.mongodb.net/eks-app?retryWrites=true&w=majority"
      AUTH_API_ADDRESSS: "auth:3000"
